[package]
name = "attester"
version = "0.1.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition = "2018"

[dependencies]
slot_clock = { path = "../slot_clock" }
ssz = { path = "../ssz" }
types = { path = "../types" }
