[package]
name = "vec_shuffle"
version = "0.1.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition = "2018"

[dependencies]
hashing = { path = "../hashing" }

[dev-dependencies]
yaml-rust = "0.4.2"
